name: Frontend Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "*.md", "frontend/.gitignore" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: AWS Login (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Build frontend
        run: |
          npm ci
          npm run build
        working-directory: frontend/

      - name: Upload to S3
        run: |
          aws s3 sync dist/* s3://luxe-ecommerce-frontend --delete
        working-directory: frontend/

      - name: Check if index.html changed
        id: index_change_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "dist/index.html"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        working-directory: frontend/
          